version: "3.3"
services:
  urbit-umbrel:
    # build: .
    image: mopfelwinrux/urbit-umbrel:latest@sha256:bcb0961ac13004001bc2864462d7cdb740d4baca8d15226f6252b2493c08ae75
    ports:
      - "34343:34343"
      - "8090:8090"
    volumes:
      - ${APP_DATA_DIR}/piers:/data/piers
      - ${APP_DATA_DIR}/keys:/data/keys
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      APP_PASSWORD: ${APP_PASSWORD}
